import type { Metadata } from "next";

import { LegalContact, LegalPage } from "@/components/layout/legal-page";

export const metadata: Metadata = {
  description: "How vidi collects, uses, stores, and shares personal data.",
  title: "Privacy policy",
};

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Your data" title="Privacy policy">
      <p>
        This Privacy Policy explains how vidi (“vidi”, “we”, “us”) handles
        information when you use the vidi movie game, website, and related
        services (the “Service”).
      </p>

      <h2>1. Information we collect</h2>
      <h3>Account and Google sign-in information</h3>
      <p>
        When you create an account, we process your email address,
        authentication identifier, and account provider. If you continue with
        Google, Google provides the basic account information you authorize,
        which may include your name, email address, profile image, and Google
        account identifier. vidi uses this information only to authenticate you,
        create your account, display your profile, maintain your session, and
        protect account access.
      </p>
      <p>
        vidi does not request access to Gmail, Google Drive, contacts,
        calendars, or other unrelated Google services. We do not sell Google
        user data, use it for advertising, or use it to train
        artificial-intelligence models.
      </p>

      <h3>Profile and social information</h3>
      <p>
        We process your username, display name, optional avatar URL, movie
        personality, movie count, game history, friendships, and pending friend
        requests. Profiles are public by default, so other people may see the
        public profile information displayed by vidi. Your email address and
        authentication credentials are not shown on your public profile.
      </p>

      <h3>Game and taste information</h3>
      <p>
        We store games you create or join, movie decks, whether you have seen a
        movie, reactions such as Love, Like, Meh, or Can&apos;t Remember, game
        progress, compatibility results, generated watchlists, and derived movie
        personalities. These answers can reveal entertainment preferences. Other
        players do not receive your individual answers while a game is active;
        relevant comparisons may be shown after results become available.
      </p>

      <h3>Guest, device, and technical information</h3>
      <p>
        Guests receive a random session identifier stored in an essential,
        HTTP-only cookie. We and our infrastructure providers may also process
        IP address, browser and device information, timestamps, request logs,
        error information, and security events needed to operate and protect the
        Service. When you are temporarily offline, unsent game answers may be
        stored locally on your device until they can be synchronized.
      </p>

      <h2>2. How we use information</h2>
      <ul>
        <li>Provide accounts, guest sessions, games, lobbies, and results.</li>
        <li>
          Generate compatibility scores, watchlists, and movie personalities.
        </li>
        <li>Maintain friendships and public profiles.</li>
        <li>
          Recover game progress and synchronize answers after disconnection.
        </li>
        <li>Detect abuse, investigate errors, and secure the Service.</li>
        <li>Comply with applicable legal obligations.</li>
      </ul>
      <p>
        Where applicable, we rely on performing our agreement with you,
        legitimate interests in operating and securing vidi, consent where
        requested, and compliance with law.
      </p>

      <h2>3. Automated processing</h2>
      <p>
        Compatibility, recommendations, and movie personalities are generated by
        deterministic software rules using your movie answers and movie
        metadata. vidi does not use an LLM to assign movie personalities. These
        playful outputs are entertainment features and do not make legal or
        similarly significant decisions about you.
      </p>

      <h2>4. When information is shared</h2>
      <p>We disclose information only as needed to:</p>
      <ul>
        <li>
          Other game participants, when showing lobby state and completed game
          comparisons.
        </li>
        <li>Other users, through public profiles and accepted friendships.</li>
        <li>
          Supabase, which provides authentication, database, and Realtime
          infrastructure.
        </li>
        <li>Vercel, which hosts and delivers the vidi application.</li>
        <li>Google, when you choose Google authentication.</li>
        <li>
          An email delivery provider, when email authentication is enabled.
        </li>
        <li>
          TMDB, for server-side movie metadata requests; vidi does not send your
          Google account credentials or individual movie reactions to TMDB.
        </li>
        <li>
          Authorities or advisers where reasonably necessary to comply with law,
          protect users, or defend legal rights.
        </li>
      </ul>
      <p>
        vidi does not sell personal information and does not run a social feed.
      </p>

      <h2>5. Cookies and local storage</h2>
      <p>
        vidi uses essential cookies for authentication and guest identity. Local
        browser storage may temporarily hold an offline answer journal so game
        progress survives connection loss. These technologies are used to
        provide requested functionality, not cross-site advertising.
      </p>

      <h2>6. Retention</h2>
      <p>
        We retain account information while your account remains active and keep
        game information for as long as needed to provide histories, results,
        and watchlists. Guest identifiers expire or are removed after account
        conversion, subject to operational backups and legal requirements. We
        may retain limited security logs for fraud prevention, troubleshooting,
        and legal compliance.
      </p>

      <h2>7. Security</h2>
      <p>
        vidi uses access controls, Row Level Security, server-only credentials,
        encrypted HTTPS connections, restricted authentication cookies, and
        validation of external input. No online service can guarantee absolute
        security. Keep access to your email and Google account secure and report
        suspected unauthorized activity promptly.
      </p>

      <h2>8. Your choices and rights</h2>
      <p>
        You can edit certain profile information, remove watchlist items, remove
        friends, decline friend requests, or sign out through the Service.
        Depending on your location, you may also have rights to access, correct,
        delete, restrict, object to, or obtain a copy of personal information,
        and to complain to a data-protection authority.
      </p>
      <p>
        To make a privacy or account-deletion request, contact <LegalContact />.
        We may need to verify that you control the relevant account before
        acting.
      </p>

      <h2>9. International processing</h2>
      <p>
        Our providers may process information in countries other than your own.
        Where required, we use lawful mechanisms and provider safeguards for
        international transfers.
      </p>

      <h2>10. Children</h2>
      <p>
        vidi is not directed to children under 13. If local law requires a
        higher age to consent to online services or data processing, a parent or
        guardian must provide the required permission. Contact us if you believe
        a child provided personal information without appropriate authorization.
      </p>

      <h2>11. Changes to this policy</h2>
      <p>
        We may update this policy as vidi changes. We will update the effective
        date and provide additional notice when a change is material. Continued
        use after a change takes effect is subject to the updated policy, where
        permitted by law.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions and privacy requests can be sent to <LegalContact />. Before
        public launch, vidi will identify its responsible legal operator and any
        additional contact details required by applicable law.
      </p>
    </LegalPage>
  );
}
